name: Release App

on: [push, pull_request]

permissions:
    contents: write # REQUIRED for GitHub Release

jobs:
    build-and-release:
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.x"

            - name: Install PyInstaller
              run: pip install pyinstaller

            - name: Build .exe with PyInstaller
              run: pyinstaller --onefile --noconsole app.py

            - name: Upload app.exe to GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ github.ref_name }}
                  name: Release ${{ github.ref_name }}
                  files: dist/app.exe # rename if needed (e.g., to app.exe)
