name: Release

on:
    push:
        tags: # run only when you push a version tag like v1.0.0
            - "v*"
    workflow_dispatch: # optional manual trigger

permissions: # 👈 give the job what it needs
    contents: write # to create the release & upload assets

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Read version
              id: get_version
              run: echo "version=$(cat .version)" >> "$GITHUB_OUTPUT"

            - name: Zip project
              run: zip -r "cicd-python-${{ steps.get_version.outputs.version }}.zip" . -x '*.git*' '*.github*'

            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                  # use the tag that triggered the workflow
                  tag_name: ${{ github.ref_name }}
                  name: ${{ github.ref_name }}
                  files: cicd-python-${{ steps.get_version.outputs.version }}.zip
